# Generated by Django 4.2.11 on 2024-08-14 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('numero_dni', models.CharField(max_length=11)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('momento_de_carga', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=1)),
                ('id_estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_civil_paciente', to='administracion.estadocivil')),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad', to='administracion.localidad')),
                ('id_obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obra_social', to='administracion.obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='administracion.pais')),
            ],
        ),
        migrations.CreateModel(
            name='PrestacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=1)),
                ('id_obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obra_social_prestacion', to='administracion.obrasocial')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='administracion.paciente')),
                ('id_prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacion', to='administracion.prestacion')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sexo', to='administracion.sexo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad', to='administracion.provincia'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('momento_de_carga', models.DateTimeField(auto_now_add=True)),
                ('id_prestacion_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacion_paciente_asistencia', to='administracion.prestacionpaciente')),
            ],
        ),
    ]
