# Generated by Django 4.1.12 on 2024-08-28 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administracion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistencia",
            name="fecha",
            field=models.DateField(auto_now_add=True, verbose_name="Fecha Asistencia"),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="hora",
            field=models.TimeField(auto_now_add=True, verbose_name="Hora Asistencia"),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="id_prestacion_paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="prestacion_paciente_asistencia",
                to="administracion.prestacionpaciente",
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="momento_de_carga",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Momento de carga"
            ),
        ),
        migrations.AlterField(
            model_name="localidad",
            name="nombre",
            field=models.CharField(max_length=50, verbose_name="Localidad"),
        ),
        migrations.AlterField(
            model_name="localidad",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="localidad",
                to="administracion.provincia",
            ),
        ),
        migrations.AlterField(
            model_name="obrasocial",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="apellido",
            field=models.CharField(max_length=150, verbose_name="Apellido/s Paciente"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="celular",
            field=models.CharField(max_length=50, verbose_name="Numero Celular"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Direccion"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="fecha_nacimiento",
            field=models.DateField(verbose_name="Fecha de nacimiento"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_estado_civil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="estado_civil_paciente",
                to="administracion.estadocivil",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_localidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="localidad",
                to="administracion.localidad",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_obra_social",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="obra_social",
                to="administracion.obrasocial",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_sexo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sexo",
                to="administracion.sexo",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nombre",
            field=models.CharField(max_length=150, verbose_name="Nombre/s Paciente"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="numero_dni",
            field=models.CharField(max_length=11, verbose_name="Numero DNI"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefono Fijo"
            ),
        ),
        migrations.AlterField(
            model_name="pais",
            name="nombre",
            field=models.CharField(max_length=50, verbose_name="Pais"),
        ),
        migrations.AlterField(
            model_name="prestacion",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_obra_social",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="obra_social_prestacion",
                to="administracion.obrasocial",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="paciente",
                to="administracion.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_prestacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="prestacion",
                to="administracion.prestacion",
            ),
        ),
        migrations.AlterField(
            model_name="provincia",
            name="nombre",
            field=models.CharField(max_length=50, verbose_name="Provincia"),
        ),
        migrations.AlterField(
            model_name="provincia",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pais",
                to="administracion.pais",
            ),
        ),
    ]
