# Generated by Django 4.1.12 on 2024-08-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "administracion",
            "0002_alter_asistencia_fecha_alter_asistencia_hora_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="id_obra_social",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="obra_social",
                to="administracion.obrasocial",
            ),
        ),
    ]
