# Generated by Django 4.1.12 on 2024-08-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0003_alter_paciente_id_obra_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="id_estado_civil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estado_civil_paciente",
                to="administracion.estadocivil",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="localidad",
                to="administracion.localidad",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_obra_social",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="obra_social",
                to="administracion.obrasocial",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="id_sexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sexo",
                to="administracion.sexo",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_obra_social",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="obra_social_prestacion",
                to="administracion.obrasocial",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paciente",
                to="administracion.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_prestacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prestacion",
                to="administracion.prestacion",
            ),
        ),
    ]
