# Generated by Django 4.1.12 on 2024-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0005_obrasocial_activo_prestacion_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="observaciones",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="obrasocial",
            name="descripcion",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
