# Generated by Django 4.1.12 on 2024-08-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0006_paciente_observaciones_alter_obrasocial_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="celular",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Numero Celular"
            ),
        ),
    ]
