# Generated by Django 4.1.12 on 2024-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0007_alter_paciente_celular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="fecha_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fin de la prestacion"
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="fecha_inicio",
            field=models.DateField(verbose_name="Inicio de la prestacion"),
        ),
    ]
