# Generated by Django 4.1.12 on 2024-08-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "administracion",
            "0007_alter_obrasocial_descripcion_alter_paciente_apellido_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_obra_social",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="obra_social_prestacion",
                to="administracion.obrasocial",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_prestacion",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="prestacion",
                to="administracion.prestacion",
            ),
        ),
    ]
