# Generated by Django 4.1.12 on 2024-08-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0008_alter_prestacionpaciente_fecha_fin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_obra_social",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="obra_social_prestacion",
                to="administracion.obrasocial",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paciente",
                to="administracion.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionpaciente",
            name="id_prestacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestacion",
                to="administracion.prestacion",
            ),
        ),
    ]
