# Generated by Django 4.1.12 on 2024-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0008_alter_prestacionpaciente_id_obra_social_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Direccion"
            ),
        ),
    ]
