# Generated by Django 4.1.12 on 2024-10-08 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administracion", "0010_alter_prestacionpaciente_id_obra_social_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("activo", models.BooleanField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name="paciente",
            name="numero_dni",
            field=models.CharField(max_length=8, verbose_name="Numero DNI"),
        ),
        migrations.CreateModel(
            name="Profesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=150, verbose_name="Apellido")),
                (
                    "numero_dni",
                    models.CharField(max_length=8, verbose_name="Numero DNI"),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Numero Celular",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Direccion"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numero Celular",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                ("momento_de_carga", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=1)),
                (
                    "id_sexo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sexo_prof",
                        to="administracion.sexo",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="usuario_prof",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfecionalTratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(verbose_name="Inicio de la prestacion"),
                ),
                ("activo", models.BooleanField(default=1)),
                (
                    "id_profecional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="profesional",
                        to="administracion.profesional",
                    ),
                ),
                (
                    "id_tratamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tratamiento",
                        to="administracion.tratamiento",
                    ),
                ),
            ],
        ),
    ]
