# Generated by Django 4.1.12 on 2024-10-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administracion",
            "0011_tratamiento_alter_paciente_numero_dni_profesional_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfecionalTratamiento",
            new_name="ProfesionalTratamiento",
        ),
        migrations.AlterField(
            model_name="profesional",
            name="matricula",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Matricula"
            ),
        ),
    ]
