# Generated by Django 4.1.12 on 2024-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administracion",
            "0013_profesional_id_localidad_alter_profesional_matricula_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tratamiento",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
