# Generated by Django 4.1.12 on 2024-10-16 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0014_tratamiento_descripcion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profesionaltratamiento",
            old_name="id_profecional",
            new_name="id_profesional",
        ),
    ]
