# Generated by Django 4.1.12 on 2024-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administracion",
            "0015_rename_id_profecional_profesionaltratamiento_id_profesional",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="numero_dni",
            field=models.CharField(
                max_length=8, unique=True, verbose_name="Numero DNI"
            ),
        ),
        migrations.AlterField(
            model_name="profesional",
            name="numero_dni",
            field=models.CharField(
                max_length=8, unique=True, verbose_name="Numero DNI"
            ),
        ),
    ]
