# Generated by Django 4.1.12 on 2024-10-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0016_alter_paciente_numero_dni_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="numero_dni",
            field=models.CharField(max_length=8, verbose_name="Numero DNI"),
        ),
        migrations.AlterField(
            model_name="profesional",
            name="numero_dni",
            field=models.CharField(max_length=8, verbose_name="Numero DNI"),
        ),
    ]
