# Generated by Django 4.1.12 on 2024-11-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0018_dia_agenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha"),
        ),
    ]
