# Generated by Django 4.1.12 on 2024-11-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0019_agenda_fecha_fin"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="id_agenda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="agenda",
                to="administracion.agenda",
            ),
        ),
    ]
