# Generated by Django 4.1.12 on 2025-04-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0022_tipopago_plan_pago_pacienteplan_cuota"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetallePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="importe"
                    ),
                ),
                (
                    "id_cuota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_cuota",
                        to="administracion.cuota",
                    ),
                ),
                (
                    "id_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_pago",
                        to="administracion.pago",
                    ),
                ),
            ],
        ),
    ]
