# Generated by Django 4.1.12 on 2025-05-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0023_detallepago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuota",
            name="anulado",
            field=models.BooleanField(default=0),
        ),
    ]
