# Generated by Django 4.1.12 on 2025-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0024_alter_cuota_anulado"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallepago",
            name="activo",
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name="pago",
            name="activo",
            field=models.BooleanField(default=1),
        ),
    ]
