# Generated by Django 4.1.12 on 2025-07-24 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administracion", "0026_area_pacientearea"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfesionalArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("momento_de_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "id_area",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_area_pro",
                        to="administracion.area",
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profesional_area",
                        to="administracion.profesional",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="usuario_pro_area",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
