# Generated by Django 4.1.12 on 2025-07-25 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0027_profesionalarea"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profesionalarea",
            old_name="id_paciente",
            new_name="id_profesional",
        ),
    ]
