# Generated by Django 4.1.12 on 2026-02-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0028_rename_id_paciente_profesionalarea_id_profesional"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuota",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
