# Generated by Django 4.1.12 on 2026-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0029_cuota_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profesional",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
