# Generated by Django 4.1.12 on 2026-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0030_paciente_email_profesional_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacientearea",
            name="activo",
            field=models.BooleanField(default=1),
        ),
    ]
