# Generated by Django 4.1.12 on 2026-08-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0031_pacientearea_activo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agenda",
            index=models.Index(
                fields=["id_prestacion_paciente", "activo", "id_dia", "hora_inicio"],
                name="agenda_pac_dia_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agenda",
            index=models.Index(
                fields=[
                    "id_profesional_tratamiento",
                    "activo",
                    "id_dia",
                    "hora_inicio",
                ],
                name="agenda_prof_dia_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(fields=["numero_dni"], name="paciente_dni_idx"),
        ),
        migrations.AddIndex(
            model_name="pacientearea",
            index=models.Index(
                fields=["id_area", "activo", "id_paciente"], name="pac_area_lookup_idx"
            ),
        ),
    ]
