from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0032_agenda_agenda_pac_dia_idx_agenda_agenda_prof_dia_idx_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="paciente",
                    name="fecha_nacimiento",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha de nacimiento",
                    ),
                ),
                migrations.AlterField(
                    model_name="paciente",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="prestacionpaciente",
                    name="fecha_inicio",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Inicio de la prestacion",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestacionpaciente",
                    name="fecha_fin",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fin de la prestacion",
                    ),
                ),
                migrations.AlterField(
                    model_name="profesional",
                    name="fecha_nacimiento",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha de nacimiento",
                    ),
                ),
                migrations.AlterField(
                    model_name="profesional",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="profesionaltratamiento",
                    name="fecha_inicio",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Inicio del Tratamiento",
                    ),
                ),
                migrations.AlterField(
                    model_name="agenda",
                    name="fecha",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha",
                    ),
                ),
                migrations.AlterField(
                    model_name="agenda",
                    name="fecha_fin",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha",
                    ),
                ),
                migrations.AlterField(
                    model_name="agenda",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="asistencia",
                    name="fecha",
                    field=models.DateField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha Asistencia",
                    ),
                ),
                migrations.AlterField(
                    model_name="asistencia",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Momento de carga",
                    ),
                ),
                migrations.AlterField(
                    model_name="pago",
                    name="fecha",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha",
                    ),
                ),
                migrations.AlterField(
                    model_name="pago",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="plan",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="pacienteplan",
                    name="fecha",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha",
                    ),
                ),
                migrations.AlterField(
                    model_name="pacienteplan",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="cuota",
                    name="imputado",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="imputado",
                    ),
                ),
                migrations.AlterField(
                    model_name="pacientearea",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="profesionalarea",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
