# Generated by Django 4.1.12 on 2024-12-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "numero_cuit",
                    models.CharField(max_length=8, verbose_name="Numero cuit"),
                ),
                ("activo", models.BooleanField(default=1)),
                ("momento_de_carga", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50, verbose_name="tipo")),
                ("serie", models.CharField(max_length=50, verbose_name="nombre")),
                ("numero", models.CharField(max_length=50, verbose_name="nombre")),
                ("fecha", models.DateField(verbose_name="fecha")),
                ("importe", models.FloatField(verbose_name="importe")),
                (
                    "id_benefiaciaro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_beneficiario",
                        to="finanzas.beneficiario",
                    ),
                ),
            ],
        ),
    ]
