# Generated by Django 4.1.12 on 2024-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiario",
            name="numero_cuit",
            field=models.CharField(max_length=50, verbose_name="Numero cuit"),
        ),
    ]
