# Generated by Django 4.1.12 on 2024-12-16 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finanzas", "0002_alter_beneficiario_numero_cuit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="id_benefiaciaro",
            new_name="id_beneficiario",
        ),
    ]
