# Generated by Django 4.1.12 on 2024-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finanzas", "0003_rename_id_benefiaciaro_factura_id_beneficiario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="serie",
            new_name="pto_vta",
        ),
        migrations.AlterField(
            model_name="factura",
            name="importe",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="importe"
            ),
        ),
    ]
