# Generated by Django 4.1.12 on 2025-01-31 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finanzas", "0004_rename_serie_factura_pto_vta_alter_factura_importe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                ("activo", models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                ("numero", models.CharField(max_length=50, verbose_name="numero")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total"
                    ),
                ),
                ("activo", models.BooleanField(default=1)),
                ("momento_de_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "id_beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_beneficiario_ordenpago",
                        to="finanzas.beneficiario",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="usuario_ordenpago",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="importe"
                    ),
                ),
                (
                    "id_factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_factura_detalleorden",
                        to="finanzas.beneficiario",
                    ),
                ),
                (
                    "id_ordenpago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_ordenpago_detalleorden",
                        to="finanzas.ordenpago",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Descuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="importe"
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Obseraciones",
                    ),
                ),
                (
                    "id_concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_concepto_dto",
                        to="finanzas.concepto",
                    ),
                ),
                (
                    "id_ordenpago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_ordenpago_dto",
                        to="finanzas.ordenpago",
                    ),
                ),
            ],
        ),
    ]
