# Generated by Django 4.1.12 on 2025-01-31 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finanzas", "0005_concepto_ordenpago_detalleorden_descuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenpago",
            name="observaciones",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Obseraciones"
            ),
        ),
        migrations.AlterField(
            model_name="detalleorden",
            name="id_factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_factura_detalleorden",
                to="finanzas.factura",
            ),
        ),
    ]
