# Generated by Django 4.1.12 on 2025-02-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finanzas", "0006_ordenpago_observaciones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleorden",
            name="activo",
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name="ordenpago",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="total",
            ),
        ),
    ]
