# Generated by Django 4.1.12 on 2025-02-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finanzas", "0007_detalleorden_activo_alter_ordenpago_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="descuento",
            name="activo",
            field=models.BooleanField(default=1),
        ),
    ]
