# Generated by Django 4.1.12 on 2025-05-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finanzas", "0008_descuento_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="descuento",
            name="importe",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="importe"
            ),
        ),
        migrations.AlterField(
            model_name="detalleorden",
            name="importe",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="importe"
            ),
        ),
        migrations.AlterField(
            model_name="ordenpago",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                null=True,
                verbose_name="total",
            ),
        ),
    ]
