# Generated by Django 4.1.12 on 2026-02-02 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0028_rename_id_paciente_profesionalarea_id_profesional"),
        (
            "finanzas",
            "0009_alter_descuento_importe_alter_detalleorden_importe_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="id_paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_paciente_factura",
                to="administracion.paciente",
            ),
        ),
    ]
