# Generated by Django 4.1.12 on 2025-08-11 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administracion", "0028_rename_id_paciente_profesionalarea_id_profesional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Derivador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre_derivador"),
                ),
                ("activo", models.BooleanField(default=1)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="usuario_derivador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadoCertificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre_estado_cert"),
                ),
                ("activo", models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="PacienteRehabilitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_tutor",
                    models.CharField(max_length=100, verbose_name="nombre_tutor"),
                ),
                (
                    "celular_tutor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="celular_tutor",
                    ),
                ),
                ("hijos", models.IntegerField(max_length=100)),
                (
                    "vencimiento_certificado",
                    models.DateField(
                        blank=True, null=True, verbose_name="vencimiento_certificado"
                    ),
                ),
                (
                    "fecha_junta",
                    models.DateField(blank=True, null=True, verbose_name="fecha_junta"),
                ),
                ("ven_presupuesto", models.BooleanField(default=0)),
                (
                    "vencimiento_presupuesto",
                    models.DateField(
                        blank=True, null=True, verbose_name="vencimiento_presupuesto"
                    ),
                ),
                ("puerto_esperanza", models.BooleanField(default=0)),
                ("momento_de_carga", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=1)),
                (
                    "id_derivador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_derivador",
                        to="rehabilitacion.derivador",
                    ),
                ),
                (
                    "id_estado_certificado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_estado_certificado",
                        to="rehabilitacion.estadocertificado",
                    ),
                ),
                (
                    "id_paciente_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_paciente_area",
                        to="administracion.pacientearea",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="usuario_pac_rehabilitacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
