# Generated by Django 4.1.12 on 2025-08-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0028_rename_id_paciente_profesionalarea_id_profesional"),
        ("rehabilitacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacienterehabilitacion",
            name="id_obra_social",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="obra_social_paciente_rehabilitacion",
                to="administracion.obrasocial",
            ),
        ),
        migrations.AlterField(
            model_name="pacienterehabilitacion",
            name="hijos",
            field=models.IntegerField(),
        ),
    ]
