# Generated by Django 4.1.12 on 2025-08-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0002_pacienterehabilitacion_id_obra_social_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre_familia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre_diagnostico"),
                ),
                ("activo", models.BooleanField(default=1)),
                (
                    "id_familia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_familia",
                        to="rehabilitacion.familia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(blank=True, null=True, verbose_name="fecha_"),
                ),
                (
                    "fecha_alta",
                    models.DateField(blank=True, null=True, verbose_name="fecha_alta"),
                ),
                ("dado_alta", models.BooleanField(default=0)),
                (
                    "id_diagnostico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_diagnostico_alta",
                        to="rehabilitacion.diagnostico",
                    ),
                ),
                (
                    "id_paciente_rehabilitacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_paciente_rehabilitacion_alta",
                        to="rehabilitacion.pacienterehabilitacion",
                    ),
                ),
            ],
        ),
    ]
