# Generated by Django 4.1.12 on 2025-08-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0003_familia_diagnostico_alta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacienterehabilitacion",
            name="ven_presupuesto",
            field=models.BooleanField(),
        ),
    ]
