# Generated by Django 4.1.12 on 2025-08-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0004_alter_pacienterehabilitacion_ven_presupuesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacienterehabilitacion",
            name="puerto_esperanza",
            field=models.BooleanField(choices=[(False, "NO"), (True, "SI")], default=0),
        ),
        migrations.AlterField(
            model_name="pacienterehabilitacion",
            name="ven_presupuesto",
            field=models.BooleanField(choices=[(False, "NO"), (True, "SI")], default=0),
        ),
    ]
