# Generated by Django 4.1.12 on 2025-12-01 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "rehabilitacion",
            "0005_alter_pacienterehabilitacion_puerto_esperanza_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AltaFuncional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Obseraciones_alta_funcional",
                    ),
                ),
                ("activo", models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticoEtiologico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre_diagnostico_etiologico"
                    ),
                ),
                ("activo", models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticoFuncional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre_diagnostico_funcional"
                    ),
                ),
                ("activo", models.BooleanField(default=1)),
                (
                    "id_diagnostico_etiologico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_diagnostico_etiologico_en_funcional",
                        to="rehabilitacion.diagnosticoetiologico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoDiscapacidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="nombre_tipo_discapacidad"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="alta",
            name="id_diagnostico",
        ),
        migrations.AddField(
            model_name="pacienterehabilitacion",
            name="diagnosticoCUD",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="diagnosticoCUD"
            ),
        ),
        migrations.DeleteModel(
            name="Diagnostico",
        ),
        migrations.DeleteModel(
            name="Familia",
        ),
        migrations.AddField(
            model_name="diagnosticoetiologico",
            name="id_tipo_discapacidad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_tipo_discapacidad",
                to="rehabilitacion.tipodiscapacidad",
            ),
        ),
        migrations.AddField(
            model_name="altafuncional",
            name="id_alta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_diagnostico_funcional",
                to="rehabilitacion.alta",
            ),
        ),
        migrations.AddField(
            model_name="altafuncional",
            name="id_diagnostico_funcional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_diagnostico_funcional",
                to="rehabilitacion.diagnosticofuncional",
            ),
        ),
        migrations.AddField(
            model_name="altafuncional",
            name="id_usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuario_alta_funcional",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alta",
            name="id_diagnostico_etiologico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_diagnostico_etiologico_alta",
                to="rehabilitacion.diagnosticoetiologico",
            ),
        ),
    ]
