# Generated by Django 4.1.12 on 2025-12-26 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0028_rename_id_paciente_profesionalarea_id_profesional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rehabilitacion", "0006_altafuncional_diagnosticoetiologico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacienterehabilitacion",
            name="hijos",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AgendaRehab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha_rehab")),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha_rehab"),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Inicio rehab")),
                ("hora_fin", models.TimeField(verbose_name="Hora de Fin rehab")),
                (
                    "tiempo",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="tiempo_rehab"
                    ),
                ),
                ("momento_de_carga", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=1)),
                (
                    "id_dia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dia_agenda_rehab",
                        to="administracion.dia",
                    ),
                ),
                (
                    "id_prestacion_paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="prestacion_paciente_agenda_rehab",
                        to="administracion.prestacionpaciente",
                    ),
                ),
                (
                    "id_profesional_tratamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="profesional_tratamiento_agenda_rehab",
                        to="administracion.profesionaltratamiento",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="usuario_agenda_rehab",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
