# Generated by Django 4.1.12 on 2025-12-29 12:15

from django.db import migrations, models
import django.db.models.deletion


def check_and_remove_fields(apps, schema_editor):
    """
    Custom function to safely remove fields if they exist.
    This prevents the 'Can't DROP key' error in MySQL.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if the table exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables 
            WHERE table_schema = DATABASE()
            AND table_name = 'rehabilitacion_agendarehab'
        """)
        
        if cursor.fetchone()[0] == 0:
            # Table doesn't exist, nothing to do
            return
        
        # Check if id_prestacion_paciente_id column exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.columns 
            WHERE table_schema = DATABASE()
            AND table_name = 'rehabilitacion_agendarehab'
            AND column_name = 'id_prestacion_paciente_id'
        """)
        
        if cursor.fetchone()[0] > 0:
            # Remove foreign key constraint first
            cursor.execute("""
                SELECT CONSTRAINT_NAME
                FROM information_schema.KEY_COLUMN_USAGE
                WHERE table_schema = DATABASE()
                AND table_name = 'rehabilitacion_agendarehab'
                AND column_name = 'id_prestacion_paciente_id'
                AND CONSTRAINT_NAME != 'PRIMARY'
            """)
            
            constraint = cursor.fetchone()
            if constraint:
                cursor.execute(f"ALTER TABLE rehabilitacion_agendarehab DROP FOREIGN KEY {constraint[0]}")
            
            # Drop the column
            cursor.execute("ALTER TABLE rehabilitacion_agendarehab DROP COLUMN id_prestacion_paciente_id")
        
        # Check if id_profesional_tratamiento_id column exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.columns 
            WHERE table_schema = DATABASE()
            AND table_name = 'rehabilitacion_agendarehab'
            AND column_name = 'id_profesional_tratamiento_id'
        """)
        
        if cursor.fetchone()[0] > 0:
            # Remove foreign key constraint first
            cursor.execute("""
                SELECT CONSTRAINT_NAME
                FROM information_schema.KEY_COLUMN_USAGE
                WHERE table_schema = DATABASE()
                AND table_name = 'rehabilitacion_agendarehab'
                AND column_name = 'id_profesional_tratamiento_id'
                AND CONSTRAINT_NAME != 'PRIMARY'
            """)
            
            constraint = cursor.fetchone()
            if constraint:
                cursor.execute(f"ALTER TABLE rehabilitacion_agendarehab DROP FOREIGN KEY {constraint[0]}")
            
            # Drop the column
            cursor.execute("ALTER TABLE rehabilitacion_agendarehab DROP COLUMN id_profesional_tratamiento_id")


def noop(apps, schema_editor):
    """No-op for reverse migration"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0028_rename_id_paciente_profesionalarea_id_profesional"),
        ("rehabilitacion", "0007_alter_pacienterehabilitacion_hijos_agendarehab"),
    ]

    operations = [
        # First, use RunPython to safely remove fields from database (without state update)
        migrations.RunPython(check_and_remove_fields, noop, elidable=True),
        
        # Then use SeparateDatabaseAndState to update Django's state without touching the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="agendarehab",
                    name="id_prestacion_paciente",
                ),
                migrations.RemoveField(
                    model_name="agendarehab",
                    name="id_profesional_tratamiento",
                ),
            ],
            database_operations=[],
        ),
        
        # Add new fields
        migrations.AddField(
            model_name="agendarehab",
            name="id_paciente_area",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_paciente_area_agenda_rehab",
                to="administracion.pacientearea",
            ),
        ),
        migrations.AddField(
            model_name="agendarehab",
            name="id_profesional_area",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_profesional_area_agenda_rehab",
                to="administracion.profesionalarea",
            ),
        ),
        migrations.AddField(
            model_name="agendarehab",
            name="id_tratamiento_rehab",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tratamiento_agenda_rehab",
                to="administracion.tratamiento",
            ),
        ),
    ]
