# Generated by Django 4.1.12 on 2025-12-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0028_rename_id_paciente_profesionalarea_id_profesional"),
        ("rehabilitacion", "0008_remove_agendarehab_id_prestacion_paciente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendarehab",
            name="fecha_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha_fin_rehab"
            ),
        ),
        migrations.AlterField(
            model_name="agendarehab",
            name="id_paciente_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_paciente_area_agenda_rehab",
                to="administracion.pacientearea",
            ),
        ),
        migrations.AlterField(
            model_name="agendarehab",
            name="id_profesional_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_profesional_area_agenda_rehab",
                to="administracion.profesionalarea",
            ),
        ),
        migrations.AlterField(
            model_name="agendarehab",
            name="id_tratamiento_rehab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tratamiento_agenda_rehab",
                to="administracion.tratamiento",
            ),
        ),
    ]
