# Generated by Django 4.1.12 on 2026-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0009_alter_agendarehab_fecha_fin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendarehab",
            name="observaciones",
            field=models.CharField(
                blank=True,
                max_length=1,
                null=True,
                verbose_name="Obseraciones_agenda_rehab",
            ),
        ),
    ]
