# Generated by Django 4.1.12 on 2026-01-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0010_agendarehab_observaciones"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsistenciaRehab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha Asistencia Rehab"
                    ),
                ),
                (
                    "hora",
                    models.TimeField(
                        auto_now_add=True, verbose_name="Hora Asistencia Rehab"
                    ),
                ),
                (
                    "momento_de_carga",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Momento de carga"
                    ),
                ),
                (
                    "id_agenda_rehab",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="agenda_rehab",
                        to="rehabilitacion.agendarehab",
                    ),
                ),
            ],
        ),
    ]
