# Generated by Django 4.1.12 on 2026-01-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0011_asistenciarehab"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsistenciaRehabTeorica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tiempo",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="tiempo_rehab_agenda_teorica",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha Asistencia Rehab"
                    ),
                ),
                (
                    "id_agenda_rehab",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="agenda_rehab_teorica",
                        to="rehabilitacion.agendarehab",
                    ),
                ),
            ],
        ),
    ]
