# Generated by Django 4.1.12 on 2026-01-25 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0012_asistenciarehabteorica"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asistenciarehabteorica",
            name="tiempo",
        ),
    ]
