# Generated by Django 4.1.12 on 2026-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0013_remove_asistenciarehabteorica_tiempo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacienterehabilitacion",
            name="pre_ingreso",
            field=models.BooleanField(default=1),
        ),
    ]
