# Generated by Django 4.1.12 on 2026-02-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0030_paciente_email_profesional_email"),
        ("rehabilitacion", "0014_pacienterehabilitacion_pre_ingreso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacienterehabilitacion",
            name="pre_ingreso",
            field=models.BooleanField(choices=[(False, "NO"), (True, "SI")], default=0),
        ),
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha Informe Rehab"
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Obseraciones_alta_funcional",
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="paciente_informe",
                        to="administracion.paciente",
                    ),
                ),
                (
                    "id_profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="profesional_informe",
                        to="administracion.profesional",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="informes_rehab/")),
                (
                    "id_informe",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_informe",
                        to="rehabilitacion.informe",
                    ),
                ),
            ],
        ),
    ]
