# Generated by Django 4.1.12 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0015_alter_pacienterehabilitacion_pre_ingreso_informe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ]
