# Generated by Django 4.1.12 on 2026-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0016_informe_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informe",
            name="fecha",
            field=models.DateField(verbose_name="Fecha_informe_rehab"),
        ),
    ]
