# Generated by Django 4.1.12 on 2026-03-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0018_alter_pacienterehabilitacion_nombre_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacienterehabilitacion",
            name="nombre_tutor",
            field=models.CharField(
                blank=True,
                default="NO",
                max_length=100,
                null=True,
                verbose_name="nombre_tutor",
            ),
        ),
    ]
