# Generated by Django 4.1.12 on 2026-03-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0019_alter_pacienterehabilitacion_nombre_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivo",
            name="id_informe",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_informe_archivo",
                to="rehabilitacion.informe",
            ),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre_link"),
                ),
                ("url", models.URLField(max_length=300, verbose_name="url")),
                (
                    "id_informe",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="id_informe_link",
                        to="rehabilitacion.informe",
                    ),
                ),
            ],
        ),
    ]
