# Generated by Django 4.1.12 on 2026-03-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0030_paciente_email_profesional_email"),
        ("rehabilitacion", "0020_alter_archivo_id_informe_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="id_profesional_tratamiento",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="profesional_tratamiento_informe",
                to="administracion.profesionaltratamiento",
            ),
            preserve_default=False,
        ),
    ]
