# Generated by Django 4.1.12 on 2026-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0021_informe_id_profesional_tratamiento"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre_link"),
                ),
            ],
        ),
    ]
