# Generated by Django 4.1.12 on 2026-03-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0022_tipoinforme"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="id_tipo_informe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_tipo_informe",
                to="rehabilitacion.tipoinforme",
            ),
        ),
    ]
