# Generated by Django 4.1.12 on 2026-03-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0023_informe_id_tipo_informe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conocer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre_conocer"),
                ),
                ("activo", models.BooleanField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name="pacienterehabilitacion",
            name="id_conocer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_conocer_pac_rehab",
                to="rehabilitacion.conocer",
            ),
        ),
    ]
