# Generated by Django 4.1.12 on 2026-03-05 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0024_conocer"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacienterehabilitacion",
            name="id_conocer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="id_conocer_pac_rehab",
                to="rehabilitacion.conocer",
            ),
        ),
    ]
