# Generated by Django 4.1.12 on 2026-03-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0025_pacienterehabilitacion_id_conocer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pacienterehabilitacion",
            name="id_conocer",
        ),
        migrations.AlterField(
            model_name="tipoinforme",
            name="nombre",
            field=models.CharField(
                blank=True,
                default=1,
                max_length=100,
                null=True,
                verbose_name="Nombre_tipo_informe",
            ),
        ),
    ]
