# Generated by Django 4.1.12 on 2026-03-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0025_pacienterehabilitacion_id_conocer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacienterehabilitacion",
            name="id_conocer",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_conocer_pac_rehab",
                to="rehabilitacion.conocer",
            ),
        ),
    ]
