# Generated by Django 4.1.12 on 2026-03-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0027_pacienterehabilitacion_id_conocer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alta",
            name="id_diagnostico_etiologico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_diagnostico_etiologico_alta",
                to="rehabilitacion.diagnosticoetiologico",
            ),
        ),
        migrations.AlterField(
            model_name="altafuncional",
            name="id_diagnostico_funcional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_diagnostico_funcional",
                to="rehabilitacion.diagnosticofuncional",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosticoetiologico",
            name="id_tipo_discapacidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_tipo_discapacidad",
                to="rehabilitacion.tipodiscapacidad",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosticofuncional",
            name="id_diagnostico_etiologico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_diagnostico_etiologico_en_funcional",
                to="rehabilitacion.diagnosticoetiologico",
            ),
        ),
    ]
