# Generated by Django 4.1.12 on 2026-03-18 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rehabilitacion', '0028_alter_alta_id_diagnostico_etiologico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta',
            name='id_diagnostico_etiologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_diagnostico_etiologico_alta_to_delete', to='rehabilitacion.diagnosticoetiologico'),
        ),
        migrations.CreateModel(
            name='AltaTipoDiscapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obseraciones_alta_tipo_discapacidad')),
                ('activo', models.BooleanField(default=1)),
                ('id_alta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_alta_tipo_discapacidad', to='rehabilitacion.alta')),
                ('id_tipo_discapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_tipo_discapacidad_alta', to='rehabilitacion.tipodiscapacidad')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_alta_tipo_discapacidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AltaEtiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obseraciones_alta_etiologico')),
                ('activo', models.BooleanField(default=1)),
                ('id_alta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_alta_etiologico', to='rehabilitacion.alta')),
                ('id_diagnostico_etiologico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_diagnostico_etiologico_alta', to='rehabilitacion.diagnosticoetiologico')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_alta_etiologico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
