# Generated by Django 4.1.12 on 2026-03-19 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0029_alter_alta_id_diagnostico_etiologico_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alta",
            name="id_diagnostico_etiologico",
        ),
    ]
