# Generated by Django 4.1.12 on 2026-04-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0030_remove_alta_id_diagnostico_etiologico"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacienterehabilitacion",
            name="numero_afiliado",
            field=models.CharField(
                default=0, max_length=50, verbose_name="numero_afiliado"
            ),
        ),
    ]
