# Generated by Django 4.1.12 on 2026-05-27 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0030_paciente_email_profesional_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rehabilitacion', '0031_pacienterehabilitacion_numero_afiliado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha turno')),
                ('hora', models.TimeField(verbose_name='Hora turno')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('REALIZADO', 'Realizado'), ('ANULADO', 'Anulado')], default='PROGRAMADO', max_length=10)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo anulacion')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha anulacion')),
                ('paciente_id', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.RESTRICT, related_name='turnos_rehabilitacion', to='administracion.paciente')),
                ('profesional_id', models.ForeignKey(db_column='profesional_id', on_delete=django.db.models.deletion.RESTRICT, related_name='turnos_rehabilitacion', to='administracion.profesional')),
                ('tratamiento_id', models.ForeignKey(db_column='tratamiento_id', on_delete=django.db.models.deletion.RESTRICT, related_name='turnos_rehabilitacion', to='administracion.tratamiento')),
                ('usuario_anulacion_id', models.ForeignKey(blank=True, db_column='usuario_anulacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_anulados_rehabilitacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
