# Generated by Django 4.1.12 on 2026-06-26 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rehabilitacion", "0032_turno"),
    ]

    operations = [
        migrations.AddField(
            model_name="turno",
            name="activo",
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name="turno",
            name="usuario_eliminador_id",
            field=models.ForeignKey(
                blank=True,
                db_column="usuario_eliminador_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turnos_eliminado_rehabilitacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
