# Generated by Django 4.1.12 on 2026-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0033_turno_activo_turno_usuario_eliminador_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="turno",
            name="motivo",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Nombre_motivo"
            ),
        ),
    ]
