# Generated by Django 4.1.12 on 2026-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0034_turno_motivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="turno",
            name="request_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="agendarehab",
            index=models.Index(
                fields=["id_paciente_area", "activo", "id_dia", "hora_inicio"],
                name="agenda_r_pac_dia_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agendarehab",
            index=models.Index(
                fields=["id_profesional_area", "activo", "id_dia", "hora_inicio"],
                name="agenda_r_prof_dia_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="turno",
            index=models.Index(
                fields=["profesional_id", "activo", "fecha", "hora"],
                name="turno_prof_fecha_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="turno",
            index=models.Index(
                fields=["paciente_id", "activo", "fecha", "hora"],
                name="turno_pac_fecha_idx",
            ),
        ),
    ]
