# Generated by Codex on 2026-08-12

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def seed_carga_inicial(apps, schema_editor):
    Situacion = apps.get_model("rehabilitacion", "Situacion")
    PacienteRehabilitacion = apps.get_model("rehabilitacion", "PacienteRehabilitacion")
    PacienteRehabilitacionSituacion = apps.get_model(
        "rehabilitacion",
        "PacienteRehabilitacionSituacion",
    )

    carga_inicial, _ = Situacion.objects.get_or_create(
        idsituacion=1,
        defaults={"nombre": "Carga inicial"},
    )

    pacientes_con_situacion = PacienteRehabilitacionSituacion.objects.values_list(
        "idpacienterehabilitacion_id",
        flat=True,
    )
    situaciones_iniciales = []
    for paciente_rehabilitacion in PacienteRehabilitacion.objects.exclude(
        id__in=pacientes_con_situacion,
    ):
        situaciones_iniciales.append(
            PacienteRehabilitacionSituacion(
                idpacienterehabilitacion=paciente_rehabilitacion,
                idsituacion=carga_inicial,
                fecha=paciente_rehabilitacion.momento_de_carga or timezone.now(),
            )
        )

    PacienteRehabilitacionSituacion.objects.bulk_create(situaciones_iniciales)


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0035_turno_request_token_agendarehab_agenda_r_pac_dia_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Situacion",
            fields=[
                ("idsituacion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "situacion",
            },
        ),
        migrations.CreateModel(
            name="PacienteRehabilitacionSituacion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateTimeField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "idpacienterehabilitacion",
                    models.ForeignKey(
                        db_column="idpacienterehabilitacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situaciones",
                        to="rehabilitacion.pacienterehabilitacion",
                    ),
                ),
                (
                    "idsituacion",
                    models.ForeignKey(
                        db_column="idsituacion",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pacientes_rehabilitacion",
                        to="rehabilitacion.situacion",
                    ),
                ),
            ],
            options={
                "db_table": "pacienterehabilitacion_situacion",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="pacienterehabilitacionsituacion",
            index=models.Index(
                fields=["idpacienterehabilitacion", "-fecha", "-id"],
                name="pacrehab_sit_ult_idx",
            ),
        ),
        migrations.RunPython(seed_carga_inicial, migrations.RunPython.noop),
    ]
