# Generated by Django 4.1.12 on 2026-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0036_situacion_pacienterehabilitacion_situacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendarehab",
            name="tiempo",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="tiempo_rehab"
            ),
        ),
        migrations.AlterField(
            model_name="pacienterehabilitacionsituacion",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
