from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("rehabilitacion", "0038_disponibilidadprofesionalrehab"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="pacienterehabilitacion",
                    name="vencimiento_certificado",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="vencimiento_certificado",
                    ),
                ),
                migrations.AlterField(
                    model_name="pacienterehabilitacion",
                    name="fecha_junta",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="fecha_junta",
                    ),
                ),
                migrations.AlterField(
                    model_name="pacienterehabilitacion",
                    name="vencimiento_presupuesto",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="vencimiento_presupuesto",
                    ),
                ),
                migrations.AlterField(
                    model_name="pacienterehabilitacion",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="pacienterehabilitacionsituacion",
                    name="fecha",
                    field=models.DateTimeField(
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="alta",
                    name="fecha",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="fecha_",
                    ),
                ),
                migrations.AlterField(
                    model_name="alta",
                    name="fecha_alta",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="fecha_alta",
                    ),
                ),
                migrations.AlterField(
                    model_name="agendarehab",
                    name="fecha",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha_rehab",
                    ),
                ),
                migrations.AlterField(
                    model_name="agendarehab",
                    name="fecha_fin",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha_fin_rehab",
                    ),
                ),
                migrations.AlterField(
                    model_name="agendarehab",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="disponibilidadprofesionalrehab",
                    name="fecha_inicio",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Inicio de disponibilidad",
                    ),
                ),
                migrations.AlterField(
                    model_name="disponibilidadprofesionalrehab",
                    name="fecha_fin",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fin de disponibilidad",
                    ),
                ),
                migrations.AlterField(
                    model_name="disponibilidadprofesionalrehab",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                    ),
                ),
                migrations.AlterField(
                    model_name="asistenciarehab",
                    name="fecha",
                    field=models.DateField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha Asistencia Rehab",
                    ),
                ),
                migrations.AlterField(
                    model_name="asistenciarehab",
                    name="momento_de_carga",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Momento de carga",
                    ),
                ),
                migrations.AlterField(
                    model_name="asistenciarehabteorica",
                    name="fecha",
                    field=models.DateField(
                        auto_now_add=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha Asistencia Rehab",
                    ),
                ),
                migrations.AlterField(
                    model_name="turno",
                    name="fecha",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha turno",
                    ),
                ),
                migrations.AlterField(
                    model_name="turno",
                    name="fecha_anulacion",
                    field=models.DateTimeField(
                        blank=True,
                        null=True,
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha anulacion",
                    ),
                ),
                migrations.AlterField(
                    model_name="informe",
                    name="fecha",
                    field=models.DateField(
                        validators=[utils.validators.validate_date_not_before_1900],
                        verbose_name="Fecha_informe_rehab",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
