# Generated by Django 4.2.11 on 2024-08-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_audiofile_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
